name: football_project_app
description: Flutter application for ball detection

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  # UI components
  cupertino_icons: ^1.0.5
  
  # TensorFlow Lite
  tflite_flutter: ^0.9.0
  tflite_flutter_helper: ^0.3.1
  
  # Image processing
  image: ^3.0.2
  camera: ^0.9.4+5
  path_provider: ^2.0.15
  permission_handler: ^10.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  
  # Add assets
  assets:
    - assets/models/
    - assets/images/